### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/sharding#3]
Hi @s1na, I wanted to stay a bit aboard by running the tests. 😄 😛

Currently these are failing with:

```shell
> ava



  ✖ No tests found in test/assembly/index.ts

  9 tests passed
  1 uncaught exception

  Uncaught exception in test/assembly/index.ts

  /PATH/sharding/test/assembly/index.ts:11

   10:
   11: const wasm = fs.readFileSync(path.join(__dirname, '../../build/optimized.wasm'))
   12:

  Error: ENOENT: no such file or directory, open '/PATH/sharding/build/optimized.wasm'
```

Is this something to be fixed or can you respectively some notes on the docs on how to prepare for this to pass?

Side question: can/should I add the labels from the other repos here or do you feel for the moment more free/flexible if this is not over-organized and you can just experiment?

**Comment by holgerd77** [comment]
Ah, have found the corresponding `asbuild` npm tasks. 😄 Maybe nevertheless add some note to the docs on occasion.

**Comment by s1na** [comment]
Haha, glad you found it :smile: Sorry there's not much documentation, I should certainly work on that more!

Re question: Sure, thanks! it'd definitely help to have it more organized, as right now it's a bit chaotic

**Comment by holgerd77** [comment]
Ok, have done.

Really exciting stuff here. 😄 👍
